IF
	Global("C0AuraQuest","GLOBAL",9)
	Global("C0AuraQuestSaveGame","MYAREA",0)
	Allegiance("C0SAITO",ENEMY)
THEN
  RESPONSE #100
	SetGlobal("C0AuraQuestSaveGame","MYAREA",1)
	SaveGame(0)
END

IF
	!InPartyAllowDead("C0Aura")
	Dead("C0Aura")
	GlobalGT("C0AuraQuest","GLOBAL",1)
	GlobalLT("C0AuraQuest","GLOBAL",13)
THEN
  RESPONSE #100
	SetGlobal("C0AuraQuest","GLOBAL",-1)
	AddJournalEntry(@10009,QUEST_DONE)
END