IF
	OnCreation()
	TriggerOverride(Lastsummonerof(Myself),GLOBAL("C0AUIN6","LOCALS",1))
THEN
  RESPONSE #100
    SetGlobal("C0MASTERRUNE","LOCALS",1)
	Continue()
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,1)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",1)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,2)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",2)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,3)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",3)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,4)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",4)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,5)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",5)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,6)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",6)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,7)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",7)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,8)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",8)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,9)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",9)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,10)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",10)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,11)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",11)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,12)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",12)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,13)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",13)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,14)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",14)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,15)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",15)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,16)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",16)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,17)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",17)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,18)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",18)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,19)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",19)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,20)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",20)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,21)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",21)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,22)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",22)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,23)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",23)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,24)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",24)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,25)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",25)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,26)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",26)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,27)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",27)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,28)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",28)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,29)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",29)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,30)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",30)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,31)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",31)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,32)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",32)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,33)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",33)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,34)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",34)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,35)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",35)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,36)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",36)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,37)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",37)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,38)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",38)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,39)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",39)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,40)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",40)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,41)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",41)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,42)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",42)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,43)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",43)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,44)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",44)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,45)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",45)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,46)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",46)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,47)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",47)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,48)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",48)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevel(Lastsummonerof(Myself),ROGUE,49)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",49)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
	OnCreation()
	ClassLevelGT(Lastsummonerof(Myself),ROGUE,49)
THEN
  RESPONSE #100
    SetGlobal("C0ArtificerRuneCount","LOCALS",50)
	SetTokenGlobal("C0ArtificerRuneCount", "LOCALS", "C0AU_RUNE")
END

IF
  Detect(Lastsummonerof(Myself))
  OR(2)
  !Global("C0ArtificerRuneCount","LOCALS",0)
  Global("C0MasterRune","LOCALS",1)
THEN
  RESPONSE #100
    FaceObject(Lastsummonerof(Myself))
    StartDialogueNoSet(Lastsummonerof(Myself))
END

IF
  Detect(Lastsummonerof(Myself))
  Global("C0ArtificerRuneCount","LOCALS",0)
  !Global("C0MasterRune","LOCALS",1)
THEN
  RESPONSE #100
    DestroySelf()
END