IF
  StateCheck(Myself,STATE_HELPLESS)
  Global("Helpless","LOCALS",0)
THEN
  RESPONSE #100
  SetGlobal("Helpless","LOCALS",1)
END

IF
  !StateCheck(Myself,STATE_HELPLESS)
  Global("Helpless","LOCALS",1)
THEN
  RESPONSE #100
  SetGlobal("Helpless","LOCALS",0)
END

IF
  !Global("Helpless","LOCALS",1)
  Die()
THEN
  RESPONSE #100
	IncrementGlobal("C0AuraEliteNinjaKilled","GLOBAL",1)
	DisplayString(Myself,~*drops potion of explosion*~)
	Wait(2)
    ReallyForceSpellDead(Myself,TRAP_FIREBALL)
END