IF
  OR(2)
    InMyArea("C0Aura")
    InPartyAllowDead("C0Aura")
  GlobalLT("BD_PLOT","GLOBAL",51)
THEN
  RESPONSE #100
    ApplySpellRES("bdresurr","C0Aura")
    SmallWait(1)
	ActionOverride("PlayerChest00",TakeCreatureItems("C0Aura",BACKPACK))
    SmallWait(1)
    ReallyForceSpellDeadRES("C0AUIN7X","C0Aura")
    ActionOverride("C0Aura",LeaveParty())
    SmallWait(1)
    ActionOverride("C0Aura",DestroySelf())
    Continue()
END