IF
  Global("bd_plot","global",250)
  !GlobalTimerNotExpired("bd_mdd410z_ot_timer","bd2000")
  Global("bd_ot_c0aura","bd2000",0)
  IfValidForPartyDialog("C0Aura")
  NextTriggerObject("C0Aura")
  Range([ENEMY.0.0.0.HOSTILES],30)
THEN
  RESPONSE #100
    SetGlobalTimer("bd_mdd410z_ot_timer","bd2000",THREE_MINUTES)
    SetGlobal("bd_ot_c0aura","bd2000",1)
    DisplayStringHead("C0Aura",~I– I didn't want this, but we're not going to lose!~)
END