// PVRZ-based bams

ACTION_FOR_EACH bamFile IN ~c0amaskc.bam~ ~c0muffyc.bam~ ~c0amagac.bam~ ~c02asunc.bam~ ~c0spikec.bam~ BEGIN
    COPY ~%MOD_FOLDER%/bams/%bamFile%~ ~override~
      LPF UPDATE_PVRZ_INDICES RET original_base_index new_base_index END
    ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
      LAF INSTALL_PVRZ
      INT_VAR
        original_base_index = original_base_index
        new_base_index = new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/pvrz/mos%original_base_index%.pvrz~
      END
    END
END

// ITEMS

COPY ~%MOD_FOLDER%/items/c0abadge.itm~ ~override~
SAY NAME1 ~Glimmershine Family Insignia~
SAY NAME2 ~Glimmershine Family Insignia~
SAY DESC ~This brass insignia is small enough to fit inside of your palm. Engraved upon it is the image of a vaguely sunflower-shaped emblem and letters of a strange language you can't understand. Along the edges are carved the words "Aurelia M. Glimmershine".~

COPY ~%MOD_FOLDER%/items/c0amaga1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 180
	  target = 1
	  timing = 2
	  parameter1 = RESOLVE_STR_REF (~Aura refuses to equip this weapon.~)
	STR_VAR
	  resource = c0ausw01
END
SAY NAME1 ~Amulet~
SAY NAME2 ~Aura's Magatama~
SAY DESC ~This mysterious, curved stone is called a 'magatama'. Though you have never seen anything like it before, it is apparently a fairly common decorative design in its place of origin, Kara-Tur. These jewels are sometimes blessed by priestesses of the Way and carried as protective talismans against chaotic and malevolent spirits.

Aura's magatama is carved from a piece of green jade and was enchanted by the Kozakuran priestess Reika Amakagami, her mentor, and as such carries great sentimental value to her, so much that she is unwilling to ever remove it.

STATISTICS:

Equipped abilities:
– Saving Throws: +2
– All attacks made against the wearer by evil or chaotic creatures receive a -2 penalty to their attack roll and any saving throws caused by such attacks are made with a +2 bonus

Weight: 0~
OUTER_SET strref = RESOLVE_STR_REF (~Aura bats your hand away with the hint of a frown on her face. "Hey, hands off!"~ [GAM_47])
APPEND item_use.2da ~c0amaga1 Aura %strref% 3~

COPY ~%MOD_FOLDER%/items/c0amaga2.itm~ ~override~
SAY NAME1 ~Amulet~
SAY NAME2 ~<CHARNAME>'s Magatama~
SAY DESC ~This mysterious, curved stone is called a 'magatama'. Though you have never seen anything like it before, it is apparently a fairly common decorative design in its place of origin, Kara-Tur. These jewels are sometimes blessed by priestesses of the Way and carried as protective talismans against chaotic and malevolent spirits.

This magatama was by Aura created as a gift to <CHARNAME> using a small piece of red agate. While its material value is low, there is a sort of simple beauty to its design.

STATISTICS:

Equipped abilities:
– Saving Throws: +1
– All attacks made against the wearer by evil or chaotic creatures receive a -2 penalty to their attack roll and any saving throws caused by such attacks are made with a +2 bonus

Weight: 0~

APPEND ~ITEMSPEC.2da~ ~C0AUIDEN  1~

COPY ~%MOD_FOLDER%/spells/c0asaku.spl~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = (icon)
      END
SAY NAME1 ~Amaterasu~
SAY NAME2 ~Amaterasu~

COPY ~%MOD_FOLDER%/items/c0auide2.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0aarea1%~
END
COPY ~%MOD_FOLDER%/items/c0auiden.spl~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = (icon - 2)
      END
SAY NAME1 ~Reveal Magic~
COPY ~%MOD_FOLDER%/items/c0auiden.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Aura's Multipurpose Protective Goggles~
SAY NAME2 ~Aura's Multipurpose Protective Goggles~
SAY DESC ~Eyewear of this sort are mass-produced in Lantanese workshops, with specific designs made for archaeologists, botanists, alchemists and those of various other professions. Aura's particular pair has been customized, combining the functionalities of several different brands to assist her in her multidisciplinary line of work.

STATISTICS:

Charge abilities (three times per day):
– Identify
– Reveal Magic: Reveal all dispellable enchantments within 50' and gain +2 to attack rolls vs. arcane casters (bards, mages, sorcerers) for one turn

Equipped abilities:
– Find Traps: +20%
– Detect Illusions: +20%
– Protection from gaze attacks
– Immunity to blindness~

COPY ~%MOD_FOLDER%/items/c0muffy.itm~ ~override~
SAY NAME1 ~Muffy the Clockwork Squirrel~
SAY NAME2 ~Muffy the Clockwork Squirrel~
SAY DESC ~Muffy is a strange machine made of metal and clockwork that serves as Aura's pet. It has a strange degree of sentience, understanding human speech and exhibiting behaviour just like a real, living squirrel, to the point where its state as an animated construct is debatable. Aura claims to have crafted Muffy herself, though how she gave it life is a secret she keeps to herself.

Regardless of how it is able to act as though it were alive, Muffy is doubtlessly a useful creation – the squirrel's stomach is a hollow compartment capable of storing small objects such as gems, potions or keys. Though the act of opening up Muffy seems rather morbid, the squirrel seems rather happy to have its 'belly' filled with valuables.

STATISTICS:

Capacity: 40 items
Weight: 0~
OUTER_SET strref = RESOLVE_STR_REF (~Muffy scurries away in fear of you, its contents clattering as it runs. "Hey, get back here!" Aura sighs. "Hope he hasn't broken anything this time..."~ [GAM_48])
APPEND item_use.2da ~c0muffy Aura %strref% 3~

COPY ~%MOD_FOLDER%/items/c0muffy.sto~ ~override~
SAY 0xc ~Muffy~

COPY ~%MOD_FOLDER%/items/c0aubook.itm~ ~override~
SAY NAME1 ~Aura's Rune Book~
SAY NAME2 ~Aura's Rune Book~
SAY DESC ~This large metal-bound book is designed to hold runes and scrolls of all kind and protect them from all sorts of natural and magical hazards.

STATISTICS:

Capacity: 100
Weight: 0~

COPY ~%MOD_FOLDER%/items/c0aubook.sto~ ~override~
SAY 0xc ~Aura's Rune Book~
/*
COPY ~%MOD_FOLDER%/items/c0axbow1.itm~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
      match_parameter1 = 0
 parameter1 = RESOLVE_STR_REF (~Paralyzed~)
END
SAY NAME1 ~Thunderbolt +6~
SAY NAME2 ~Thunderbolt +6~
SAY DESC ~This strange bronze-colored contraption appears to be some sort of launcher. Its creator and late owner, Liro Mideveningwalker, was an intelligent yet ambitious gnome, and often sought out mysteries and secrets in dangerous places to increase her own knowledge. Her inexperience in combat led her to design this powerful cannon as a means for self defense. This weapon fires deadly lightning bolts that can strike down anything in its path. Liro's creativity also led her to add a variety of other implements to make it more effective. However, the energy that powers the weapon is limited and requires proper tools to recharge after too many uses. Between the cannon's notable weight and complex mechanisms, only a select few would be capable of using it effectively.

STATISTICS:

Equipped abilities:
– Armor Class: +6 vs. melee weapons
– Attacks per round set to 2
– Increased visual range
– Electrical Resistance: +100%

Combat abilities:
– The Thunderbolt does not launch projectiles. Instead, it fires a ray of lightning which deals 6d6+10 (save vs. breath weapons for half) electrical damage to all creatures within its line of fire and paralyzes them for two rounds on a failed save vs. breath. All targets struck are also Magnetized (-2 to AC vs. missiles and -20% missile damage resistance) for five rounds. The Thunderbolt strikes as a +6 weapon and may be fired 80 times before needing to recharge.

Speed Factor: 5
Proficiency Type: None
Type: Two-handed
Requires:
 14 Strength
 17 Intelligence

Weight: 20~
WRITE_SHORT 0x9C ~%c0athund%~
*/
COPY ~%MOD_FOLDER%/items/c0aubow.spl~ ~override~
SAY NAME1 ~Create Sunshooter Arrows~
SAY NAME2 ~Create Sunshooter Arrows~
COPY_EXISTING ~c0aubow1.spl~ ~override/c0aubow2.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 214 // display string
	STR_VAR
	  resource = C0AUAR01
END
COPY_EXISTING ~c0aubow1.spl~ ~override/c0aubow3.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 214 // display string
	STR_VAR
	  resource = C0AUAR02
END
COPY_EXISTING ~c0aubow1.spl~ ~override/c0aubow4.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 214 // display string
	STR_VAR
	  resource = C0AUAR03
END
COPY_EXISTING ~c0aubow1.spl~ ~override/c0aubow5.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 214 // display string
	STR_VAR
	  resource = C0AUAR04
END
COPY_EXISTING ~c0auar1a.spl~ ~override/c0auar1z.spl~
  LPF DELETE_EFFECT
    INT_VAR
      match_opcode = 146 // display string
END
COPY_EXISTING ~c0auar2a.spl~ ~override/c0auar2z.spl~
  LPF DELETE_EFFECT
    INT_VAR
      match_opcode = 146 // display string
END
COPY_EXISTING ~c0auar3a.spl~ ~override/c0auar3z.spl~
  LPF DELETE_EFFECT
    INT_VAR
      match_opcode = 146 // display string
END
COPY_EXISTING ~c0auar1a.spl~ ~override/c0auar1b.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 146 // display string
	STR_VAR
	  resource = C0AUBOW2
END
COPY_EXISTING ~c0auar2a.spl~ ~override/c0auar2b.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 146 // display string
	STR_VAR
	  resource = C0AUBOW2
END
COPY_EXISTING ~c0auar3a.spl~ ~override/c0auar3b.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 146 // display string
	STR_VAR
	  resource = C0AUBOW2
END
COPY_EXISTING ~c0auar1a.spl~ ~override/c0auar1c.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 146 // display string
	STR_VAR
	  resource = C0AUBOW3
END
COPY_EXISTING ~c0auar2a.spl~ ~override/c0auar2c.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 146 // display string
	STR_VAR
	  resource = C0AUBOW3
END
COPY_EXISTING ~c0auar3a.spl~ ~override/c0auar3c.spl~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 146 // display string
	STR_VAR
	  resource = C0AUBOW3
END

OUTER_SET sunshooter = RESOLVE_STR_REF (~Configure~)
APPEND ~ITEMDIAL.2da~ ~C0AUBO1A    %sunshooter%    C0AUBOW
C0AUBO1B    %sunshooter%    C0AUBOW
C0AUBO1C    %sunshooter%    C0AUBOW
C0AUBO2A    %sunshooter%    C0AUBOW
C0AUBO2B    %sunshooter%    C0AUBOW
C0AUBO2C    %sunshooter%    C0AUBOW
C0AUBO3A    %sunshooter%    C0AUBOW
C0AUBO3B    %sunshooter%    C0AUBOW
C0AUBO3C    %sunshooter%    C0AUBOW
C0AUBO4A    %sunshooter%    C0AUBOW
C0AUBO4B    %sunshooter%    C0AUBOW
C0AUBO4C    %sunshooter%    C0AUBOW
C0AUBO5A    %sunshooter%    C0AUBOW
C0AUBO5B    %sunshooter%    C0AUBOW
C0AUBO5C    %sunshooter%    C0AUBOW~

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/C0AUBOW.d~
COPY ~%MOD_FOLDER%/items/c0aubo1a.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter I~
SAY NAME2 ~Sunshooter I~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Rapid
  +1/2 attacks per round, -2 damage

Charge abilities (1x/day):
– Create five Sunshooter Arrows (Healing)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 for 5 rounds

THAC0: +1
Speed Factor: 2
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo1b.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter I~
SAY NAME2 ~Sunshooter I~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Precise
  +5% Critical Hit Chance, -1/2 attacks per round

Charge abilities (1x/day):
– Create five Sunshooter Arrows (Healing)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 for 5 rounds

THAC0: +3
Speed Factor: 2
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo2a.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter II~
SAY NAME2 ~Sunshooter II~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Rapid
  +1/2 attack per round, -1 damage

Charge abilities (1x/day):
– Create five Sunshooter Arrows (Healing, Lightning)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +2
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo2b.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter II~
SAY NAME2 ~Sunshooter II~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Precise
  +5% Critical Hit Chance, -1/2 attacks per round

Charge abilities (1x/day):
– Create five Sunshooter Arrows (Healing, Lightning)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +4
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo2c.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter II~
SAY NAME2 ~Sunshooter II~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Power
  Attacks deal maximum damage

Charge abilities (1x/day):
– Create five Sunshooter Arrows (Healing, Lightning)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: -2
Damage: +2
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo3a.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter III~
SAY NAME2 ~Sunshooter III~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Rapid
  +1 attack per round, -2 damage

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +3
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo3b.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter III~
SAY NAME2 ~Sunshooter III~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Precise
  +10% Critical Hit Chance, -1/2 attacks per round

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +5
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo3c.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter III~
SAY NAME2 ~Sunshooter III~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Power
  Attacks deal maximum damage

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: -1
Damage: +3
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo4a.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter IV~
SAY NAME2 ~Sunshooter IV~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Rapid
  +1 attack per round, -1 damage

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning, Static)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +4
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo4b.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter IV~
SAY NAME2 ~Sunshooter IV~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Precise
  +10% Critical Hit Chance, -1/2 attacks per round

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning, Static)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +6
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo4c.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter IV~
SAY NAME2 ~Sunshooter IV~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Power
  Attacks deal maximum damage

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning, Static)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

Damage: +4
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo5a.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter V~
SAY NAME2 ~Sunshooter V~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Rapid
  +3/2 attacks per round, -1 damage

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning, Static, Disruptor)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +5
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo5b.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter V~
SAY NAME2 ~Sunshooter V~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Precise
  +15% Critical Hit Chance, -1/2 attacks per round

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning, Static, Disruptor)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

THAC0: +8
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0aubo5c.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Sunshooter V~
SAY NAME2 ~Sunshooter V~
SAY DESC ~The Sunshooter is Aura's personal weapon, a metallic bow of unusual design that fires arrows with almost inhuman speed and accuracy. Various attachments decorate the arc of the bow, some useful (such as enchantments that alter the effects of nocked arrows) and others purely for accessory. Its complexity is so great that no one besides its creator is likely capable of understanding how to properly wield it.

STATISTICS:

– Configuration: Power
  Attacks deal maximum damage

Charge abilities (1x/day):
– Create ten Sunshooter Arrows (Healing, Lightning, Static, Disruptor)

Combat abilities:
– Magnetism: Each hit reduces target's Armor Class vs. Ranged Weapons by 1 and Missile Resistance by 3% for 5 rounds

Damage: +6
Speed Factor: 1
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 6 Strength

Weight: 2~

COPY ~%MOD_FOLDER%/items/c0auarow.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Healing Arrow~
SAY NAME2 ~Healing Arrow~
SAY DESC ~This unusual arrow, designed and crafted by Aura, deals no damage to its target, instead injecting a healing solution into their bloodstream causing their wounds to regenerate.

STATISTICS:

Combat abilities:
– Heals target for 1d6+1 hit points (does not apply Magnetism)

Damage: None
Launcher: Bow

Weight: 0~
WRITE_SHORT 0x9C ~%c0auaro1%~

COPY ~%MOD_FOLDER%/items/c0auaro2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Lightning Arrow~
SAY NAME2 ~Lightning Arrow~
SAY DESC ~This unusual arrow, designed and crafted by Aura, is charged with a huge amount of electricity which is released when the arrow strikes at a target, electrocuting them as well as all enemies around them.

STATISTICS:

Combat abilities:
– Deals electrical damage that penetrates through all targets in its path, applying Magnetism (-2 penalty to AC vs. missiles and -20% missile damage resistance) to all creatures struck for five rounds

Damage: 1d6+4 electrical
Launcher: Bow

Weight: 0~
WRITE_SHORT 0x9C ~%c0auaro2%~

COPY ~%MOD_FOLDER%/items/c0auaro3.itm~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
      match_parameter1 = 0
 parameter1 = RESOLVE_STR_REF (~Paralyzed~)
END
COPY ~%MOD_FOLDER%/items/c0auaro3.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Aura~)
	STR_VAR
	  resource = C0Aura
END
SAY NAME1 ~Static Arrow~
SAY NAME2 ~Static Arrow~
SAY DESC ~This unusual arrow, designed and crafted by Aura, is charged with a huge amount of electricity which is released when the arrow strikes a target, trapping them in a web-like formation.

STATISTICS:

Combat abilities:
– Target must make a save vs. death at -2 or be paralyzed and suffer from a -50% penalty to electrical resistance for five rounds.

THAC0: +2
Damage: 1d6+4 electrical
Launcher: Bow

Weight: 0~
WRITE_SHORT 0x9C ~%c0auaro3%~

COPY ~%MOD_FOLDER%/items/c0autt01.itm~ ~override~
SAY NAME1 ~Burst Orb~
SAY NAME2 ~Burst Orb~
SAY DESC ~This shimmering glass orb, roughly the size of a clenched fist, crackles with electricity.

STATISTICS:

Charge abilities (one use):
– When a Burst Orb is launched at the targeted area, it erupts into a mass of energy, dealing electrical damage and sending all targets away from the center of impact as well as knocking them unconscious for one round.
  Damage: 4d6+2 electrical
  Range: 30 ft.
  Area of Effect: 10' radius
  
Requires:
  9 Intelligence
  
Weight: 1~
WRITE_SHORT 0x9C ~%c0aburst%~

COPY ~%MOD_FOLDER%/items/c0agem1.itm~ ~override~
SAY NAME1 ~Ice Crystal~
SAY NAME2 ~Ice Crystal~
SAY DESC ~This crystal initially appears to be a normal shard of ice, though it does not melt even when held in hand. It seems to almost hum with latent magical energy.

STATISTICS:

Weight: 0~

COPY_EXISTING ~dezkie.cre~ ~override/dezkie.cre~
	PATCH_IF (SOURCE_SIZE > 0x2d3) THEN BEGIN
		ADD_CRE_ITEM ~c0agem1~ #0 #0 #0 ~NONE~ ~inv~
	END
BUT_ONLY_IF_IT_CHANGES

COPY ~%MOD_FOLDER%/items/c0autt02.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~Shattered~)
  END
COPY ~%MOD_FOLDER%/items/c0freeze.spl~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = (icon - 3)
      END
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~Frozen~)
  END
COPY ~%MOD_FOLDER%/items/c0autt02.itm~ ~override~
SAY NAME1 ~Cryonics Rod~
SAY NAME2 ~Cryonics Rod~
SAY DESC ~This thin metallic rod contains an essence of ice, a crystal developed in the Para-Elemental Plane of Ice which somehow found its way into the Prime Material Plane. Aura used the crystal as a power source for this rod, which focuses its energy into a weaponized beam of cold capable of freezing its targets solid.

Unlike most magical wands, it is activated through pressing a button at the base of the rod instead of a magical command word, allowing it to be used by anyone.

STATISTICS:

Charge abilities (once per day):
– Launches a ray of extreme cold towards the target, dealing cold damage and freezing the target for one turn on a failed Save vs. Wands at -2. While frozen, the target suffers double damage from physical and fire damage but is immune to cold damage. After five rounds have passed or upon taking damage, the target will be Shattered, becoming unfrozen and suffering a -2 penalty to Armor Class and Strength for one turn.
  Damage: 6d6 cold (Save vs. Wand at -2 for half)
  Range: 30 ft.
  Area of Effect: 1 creature
  
Requires:
  9 Intelligence
  
Weight: 1~

COPY ~%MOD_FOLDER%/items/c0autt03.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (~Neera~)
	STR_VAR
	  resource = neera
END
SAY NAME1 ~Aura's Wildsurge Amplifier~
SAY NAME2 ~Aura's Wildsurge Amplifier~
SAY DESC ~This experimental device is designed by Aura to amplify the abilities of a wild mage and allow them to surge at will. It appears to do so successfully, though Neera seems none too thrilled for wearing it, as its design is less than appealing.

STATISTICS:

Charge abilities (once per day):
– Rapid Surge: For the next round, the wearer may cast without delay and has casting time reduced by 4. However, every spell cast during this time will incur a wild surge.

Equipped abilities:
– +10% probability that a wild surge will have positive effect
– +2 bonus 1st level spells

Weight: 0~

COPY ~%MOD_FOLDER%/items/c0autt04.itm~ ~override~
SAY NAME1 ~Aura's Invisibility Device~
SAY NAME2 ~Aura's Invisibility Device~
SAY DESC ~This unusual looking metal device appears to function like a wand, except that it is activated through the push of a button rather than a command word, allowing anyone to use it with ease. When activated, it releases a shimmering sphere of light which envelops the user and <PRO_HISHER> allies, turning them invisible. It has apparently seen frequent use, as Aura claimed to have used it to evade bandits during her travels.

STATISTICS:

Charge abilities:
– Causes all allied creatures within the radius to turn invisible
  Range: Self
  Radius: 30'
  Duration: 10 turns
 
Weight: 1~

COPY ~%MOD_FOLDER%/items/c0bandol.itm~ ~override~
SAY NAME1 ~Bandolier~
SAY NAME2 ~Bandolier~
SAY DESC ~This bandolier was designed by Aura to safely carry firebombs and explosives of all kinds.

STATISTICS:

Capacity: 100

Weight: 0~

COPY ~%MOD_FOLDER%/items/c0bandol.sto~ ~override~
SAY 0xc ~Bandolier~

COPY ~%MOD_FOLDER%/items/c0abomb1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Green Flaming Oil~
SAY DESC ~Inside of this glass pot is an expensive mixture of oil and other chemicals. When this mixture is set ablaze, it burns for several seconds at a very hot temperature.  Flaming oil is sometimes difficult to use because it takes a long time for the user to properly throw it. Adventurers often carry oil with them to deal with trolls in the unfortunate event that they are encountered.

Aura's flasks use a specially-made type of oil which releases a highly flammable gas. The flames are emerald green, just like the oil itself.

STATISTICS:

When thrown, releases a cloud which deals 2d3 fire damage per round to all creatures within it (save vs. breath weapons at -2 for half). The cloud lasts for five rounds.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj2%~
WRITE_LONG 0x34 250

COPY ~%MOD_FOLDER%/items/c0abomb2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~White Flashbomb~
SAY DESC ~This flask contains an alchemical compound which, when detonated, explodes with a flash of light that stuns and blinds all within the vicinity.

STATISTICS

When thrown, deals 2d4 non-lethal damage and blinds all creatures within a 10' radius for five rounds on a failed save vs. breath weapons. Additionally, argets who fail a save vs. breath weapons at +2 are stunned for two rounds.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj3%~
WRITE_LONG 0x34 750

COPY ~%MOD_FOLDER%/items/c0abomb3.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Spiked Firebomb~
SAY DESC ~This spiked metal object is an explosive which unleashes a fiery blast while launching sharp metal shrapnel at anyone within a certain range of it.

STATISTICS

When thrown, deals 1d6+5 fire and 1d6+5 piercing damage within a 10' radius and causes targets to bleed for 2 points of piercing damage every round for five rounds on a failed save vs. breath weapons.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj4%~
WRITE_LONG 0x34 750

COPY ~%MOD_FOLDER%/items/c0abomb4.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Sulfide Bomb~
SAY DESC ~This explosive contains a huge amount of sulfur, which when released creates a cloud of foul-smelling and toxic fumes that can knock out a man within seconds.

STATISTICS

When thrown, releases a cloud for three rounds which deals 2d6 poison damage per round and knocks all targets unconscious for five rounds on a failed save vs. breath weapons.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj5%~
WRITE_LONG 0x34 1000

COPY ~%MOD_FOLDER%/items/c0abomb5.itm~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
 parameter1 = RESOLVE_STR_REF (~Blinded~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Crimson Smoke Canister~
SAY DESC ~This round tube, when thrown, releases a thick cloud of crimson-colored toxic smoke which impairs vision and physically weakens all creatures that breathe it.

STATISTICS

When thrown, releases a cloud for one turn which deals 4 poison damage per round. Creatures standing in the cloud must make an initial save vs. breath weapons at -2 or become blinded. Creatures must additionally make a save vs. breath weapons each round at -4 or suffer a penalty of 2 points to Armor Class, THAC0 and Constitution for three rounds.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj6%~
WRITE_LONG 0x34 1200

COPY ~%MOD_FOLDER%/items/c0abomb6.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Adhesive Bomb~
SAY DESC ~This canister contains a substance which rapidly congeals when exposed to air, becoming a burning hot and sticky glue which impairs the movements of those within its vicinity.

STATISTICS

When thrown, deals 2d8 fire damage and slows all targets for three rounds on a failed save vs. breath weapons at -2. The glue remains on the ground for three rounds before dissolving.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj7%~
WRITE_LONG 0x34 1500

COPY ~%MOD_FOLDER%/items/c0abomb7.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Corrosive Bomb~
SAY DESC ~This canister contains a heavily acidic substance which bursts into a cloud of corrosive acid when detonated, dealing severe injury to anyone unfortunate enough to stand within the vicinity.

STATISTICS

When thrown, releases an acidic cloud which deals 2d10 acid damage each turn. Enemies standing within the cloud suffer a -50% penalty to physical damage resistance. The cloud remains for five rounds.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj8%~
WRITE_LONG 0x34 2500

COPY ~%MOD_FOLDER%/items/c0aburn.spl~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = (icon - 1)
      END
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~Burning~)
  END
COPY ~%MOD_FOLDER%/items/c0abomb8.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Dread Flame Bomb~
SAY DESC ~This canister contains a powder made from a hybrid of glow powder and Shou explosive powder. The purple flames that burst from the explosive deal horrifying damage and inflict terror in any survivors.

STATISTICS

When thrown, unleashes a fireball that deals 8d8 fire damage. Victims have their total fire resistance halved for one turn and must make a save vs. breath weapons at -6 or become ignited, suffering 10% of their maximum hit points each round and fleeing in terror for five rounds.

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj9%~
WRITE_LONG 0x34 3500

COPY ~%MOD_FOLDER%/items/c0abomb9.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0AURA~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Artificer~)
END
SAY NAME1 ~Firebomb~
SAY NAME2 ~Yin-Yang Bomb~
SAY DESC ~This devastating explosive contains a special compound crafted from smokepowder, arcane magic, and Kozakuran divine incantations. The powerful magic within the explosive is somehow partially sentient, as it is intended to shift the world towards equilibrium. Those with discord in their hearts suffer extreme damage while those in perfect harmony will feel a mere shock.

STATISTICS

When thrown, unleashes a multicolored explosion which deals 2d6 magical damage and an additional amount of variant damage depending on the target's alignment (save vs. breath weapons to take half additional damage) and apply an additional effect for five rounds:
  vs. True Neutral: no bonus damage or effect
  vs. Chaotic: +6d6 fire damage, -20% damage dealt
  vs. Lawful: +6d6 cold damage, -2 Armor Class
  vs. Good: +6d6 acid damage, +20% all resistances
  vs. Evil: +6d6 electrical damage, -2 Saving Throws

Weight: 0~
WRITE_SHORT 0x9C ~%c0aproj0%~
WRITE_LONG 0x34 4000

COPY_EXISTING ~scrl2j.itm~ ~override/c0ascrl1.itm~
SAY NAME1 ~Strange Letter~
SAY NAME2 ~Strange Letter~
SAY UNIDENTIFIED_DESC ~This letter was left behind on the bodies of one of the elite ninja sent to capture Aura.

"Our quarry has entered into our domain. Seek her out and kill all who try to stand in your way. Capture her alive if possible, but if she chooses to resist, do not hesitate to eliminate her. When the task is complete, raise the signal at the city's bridge during the midnight hour and await my arrival.

Remember the oaths you have sworn and know that your success will free us from the curse of which we have been bound. Do not fail me."~

COPY_EXISTING ~scrl2j.itm~ ~override/c0ascrl2.itm~
SAY NAME1 ~Note~
SAY NAME2 ~Note~
SAY UNIDENTIFIED_DESC ~This hastily-scribbled note was left behind by Aura.

"Thank you for everything we've done together, but I can't ask you to fight this battle for my sake. Hopefully I'll make it back, but if I don't... please don't miss me."~

COPY_EXISTING ~misc1c.itm~ ~override/c0ascrl3.itm~
SAY NAME1 ~Scroll~
SAY NAME2 ~Fubuki's Records~
SAY UNIDENTIFIED_DESC ~This heavy scroll's contents are written entirely in Kara-Turan. According to Aura, they contain several years' worth of Fubuki's gathered records and information on past events involving Tadahashi Saito's war against the holy temples of Kozakura.~

COPY ~%MOD_FOLDER%/items/c0amask1.spl~ ~override~
COPY ~%MOD_FOLDER%/items/c0amask1.itm~ ~override~
SAY NAME1 ~Oni Mask~
SAY NAME2 ~Oni Mask~
SAY DESC ~This ceramic mask is a depiction of an oni, a terrifying demonic spirit from Kozakura. Its mere appearance is capable of instilling dread within those who look upon it.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Wisdom: +1
– Charisma: -2
– All enemies within 5 ft of the wearer suffer a -1 penalty to THAC0, damage, armor class and all saving throws.

Weight: 1~

COPY ~%MOD_FOLDER%/items/c0aclub1.spl~ ~override~
COPY ~%MOD_FOLDER%/items/c0aclub1.itm~ ~override~
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = (icon - 1)
      END
SAY NAME1 ~Onibi-no-kozuchi +2~
SAY NAME2 ~Onibi-no-kozuchi +2~
SAY DESC ~This heavy bludgeon is known as a kanabo, a spiked club wielded by warriors of Kara-Tur. The jagged cracks and bloodstains on the hard laquered wood suggest a past history of warfare and bloodshed. Its former owner, the violent warrior priest Kagutsuchi, enhanced it with the power of fire magic and fury.

STATISTICS:

Combat abilities:
– Each hit has a 20% chance to inflict the target with Burning Thorns, dealing 1d6 immediate piercing damage and an additional point of fire damage every round for three rounds.

Equipped abilities:
– When the wielder falls below 50% maximum hit points, <PRO_HESHE> gains a +2 bonus to damage but a -2 penalty to Armor Class.

THAC0: +2
Damage: 1d6+2, +1d4 fire damage
Damage type: crushing
Speed Factor: 4
Proficiency Type: Club
Type: One-handed
Requires:
 5 Strength

Weight: 3~

COPY ~%MOD_FOLDER%/items/c0auswfa.itm~ ~override~
SAY NAME1 ~Katana~
SAY NAME2 ~Masterwork Katana~
SAY DESC ~This katana was designed by Aura for her former friend, Tadahashi Saito, an exiled Kozakuran samurai. With the samurai slain, what Aura intends to do with the sword is unknown.

Weight: 4~

COPY ~%MOD_FOLDER%/items/c0ausw01.itm~ ~override~
SAY NAME1 ~Katana~
SAY NAME2 ~Blade of Howling Souls +2~
SAY UNIDENTIFIED_DESC ~The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d10 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength
 16 Dexterity
 14 Intelligence

Weight: 6~
SAY DESC ~This masterwork katana, claimed to be blessed by a Kara-Turan deity, was the finest creation of Aura, yet its history is a gruesome one stained with the blood of countless innocents. Although at first glance it appears to simply be a standard yet flawless blade, a wielder that is aware of its secret may reshape it to function as a deadly throwing weapon.

STATISTICS:

Combat abilities:
– Returns to the wielder's hand when thrown
– Disarm: 10% chance (40% chance in melee) to disarm opponent, reducing their attacks per round to 0 for 1 round (save vs. death to avoid)
– Critical hits deal an additional 1d10+4 slashing damage

Equipped abilities:
– 1/2 extra attack per round

THAC0: +2
Damage (melee): 1d10+4
Damage (ranged): 1d4+2
Damage type: slashing
Speed Factor: 2
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength
 16 Dexterity
 14 Intelligence

Weight: 4~
SAY 0x1D6 ~Disarmed~
SAY 0x206 ~Disarmed~

COPY ~%MOD_FOLDER%/items/c0ausw02.itm~ ~override~
SAY NAME1 ~Wakizashi~
SAY NAME2 ~Jin'u +1~
SAY UNIDENTIFIED_DESC ~The wakizashi, or companion sword, is extremely important to samurai. It is worn at all times, even indoors, and is near the samurai when he sleeps at night. As finely made as the katana, the wakizashi, a shorter sword with a length between twelve and twenty-four inches, is a dangerous weapon in the hands of a skilled user.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 3
Proficiency Type: Scimitar/Wakizashi/Ninja-to
Type: One-handed
Requires:
 5 Strength

Weight: 3~
SAY DESC ~This wakizashi has a blade sharper and finer than any other weapon you have seen, as though the slightest touch from its edge could sever steel. Its lightness and fine balance is only matched by its powerful enchantments and its beauty, decorated with faint etchings on the blade that resemble a strange hybrid of birds and clouds.

According to Aura, the sword's name roughly translates to 'Swift Wing'.

STATISTICS:

Combat abilities:
– Critical Hit Chance: +5%

Equipped abilities:
– Dexterity: +1
– Movement Rate: +2

THAC0: +1
Damage: 1d8+3 (piercing)
Speed Factor: 2
Proficiency Type: Scimitar/Wakizashi/Ninja-to
Type: One-handed
Requires:
 5 Strength

Weight: 2~
/*
COPY ~%MOD_FOLDER%/items/c0akat01.spl~ ~override~
COPY ~%MOD_FOLDER%/items/c0akat02.spl~ ~override~
COPY ~%MOD_FOLDER%/items/c0akat03.spl~ ~override~
COPY ~%MOD_FOLDER%/items/c0ausw03.spl~ ~override~
  LPF ADD_SPELL_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      opcode = 139 // display string
	  target = 2
	  parameter1 = RESOLVE_STR_REF (~Disarmed~)
	  savingthrow = 4
	  savebonus = %-2%
  END
COPY ~%MOD_FOLDER%/items/c0ausw03.itm~ ~override~
SAY NAME1 ~Katana~
SAY NAME2 ~Han'men-Akatsuki +5~
SAY DESC ~This flawless katana is the epitome of Kara-Turan swordsmithing. Forged out of a sheet of pure, red-colored steel folded upon itself a million times, its fine balance and a razor-sharp edge that never fades makes it a truly unparalleled weapon among its kind. The wielder of this katana can almost feel guided by its natural motions, guiding the blade as it weaves and flows, striking lethal blows over and over again.

STATISTICS:

Combat abilities:
– Every third successful attack is a guaranteed critical hit (resets after one round of not attacking)
– Wielder's weapon speed factor is decreased by one for two rounds on each successful hit
– On a critical hit, disarms opponent unless a save vs. death at -2 is made. Disarmed opponents are unable to attack for one round.
– 2% chance to slay target instantly on hit (chances are doubled on a critical hit) unless a save vs. death is made.

Equipped abilities:
– Armor Class: +5 vs. melee weapons

THAC0: +5
Damage: 1d10+1 (slashing)
Speed Factor: 5
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength
 18 Dexterity
 15 Intelligence

Weight: 4~
*/
COPY ~%MOD_FOLDER%/items/c0auim01.itm~ ~override~
SAY NAME1 ~Two-handed Sword~
SAY NAME2 ~Two-handed Sword, Cursed Berserking +3~
SAY DESC ~This is a cursed sword which performs perfectly under every test, save the heat of battle. Upon entering combat, the wielder will immediately go berserk, killing everything within reach until either calming down or falling unconscious. A very powerful sword, but one must decide whether or not it is worth the risk. Even once the battle fury has ended, this sword can only be removed via an exorcism using a Remove Curse spell.

Aura's enhancements to the weapon were unsuccessful in removing the curse, but somewhat successful in suppressing the rage that overcomes the wielder... at least, so long as they retain the physical and mental fortitude to hold it back. Should they allow the fury to overwhelm them, they would gain incredible strength from the unleashed power... but at a risky cost.

STATISTICS:

Equipped abilities:
– May only be removed with a Remove Curse spell
– When below 50% maximum health, the wielder must make a save vs. spell at -4 every round or go berserk, gaining +2 to Strength and +4 to damage rolls but reducing armor class by 2. Additionally, the wielder loses 1d4 hit points per round for as long as they remain enraged.

THAC0: +1
Damage: 1d10+1 (slashing)
Speed Factor: 7
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15~

COPY ~%MOD_FOLDER%/items/c0auim02.itm~ ~override~
SAY NAME1 ~Longbow~
SAY NAME2 ~The Killing Shot +3~
SAY DESC ~Longbow of Marksmanship: The Killing Shot
Driven by years of rivalry, the dukes of Spandeliyon and Delthuntle decided to organize a private contest that would proclaim the better archer between them. Both boasted the power of their magical bows, but that wasn't enough for Edwall Dest, Duke of Spandeliyon. He arranged for the theft of his opponent's bow, and on the day of the contest, he couldn't help gloat in his advantage. The Duke of Delthuntle, known only as Raymond, demanded a demonstration of Edwall's skill on a scarecrow that he had placed. Edwall Dest drew his longbow and released the arrow with determination, not stopping to think how uncannily the target resembled himself. The missile split the large voodoo doll's head in twain, and at that moment, Edwall's head did much the same.

Aura's enhancements to the weapon include reshaping it into a composite weapon and adding several strange attachments. The bow has become significantly heavier and more difficult to draw as a consequence, but now fires mighty shots capable of shattering the most sturdy of defenses.

STATISTICS:

Combat abilities:
– Sets attacks per round to 1
– Critical Hit Chance: +10% (this weapon)
– Armor Breaker: Critical hits deal an additional 1d10 piercing damage and reduces the target's Armor Class by 4 points for two rounds.

THAC0: +6
Damage: +1 (plus Strength bonus)
Speed Factor: 9
Proficiency Type: Longbow
Type: Two-handed
Requires:
 17 Strength

Weight: 8~

COPY ~%MOD_FOLDER%/items/c0auim03.itm~ ~override~
SAY NAME1 ~Quarterstaff~
SAY NAME2 ~Silver Staff Mace +2~
SAY DESC ~This weapon appears to be a normal large walking staff, but it has a faint aura of alteration magic. Uttering the command word causes the staff to assume the attributes of a mace, allowing it to be wielded with one hand. This was likely designed for Clerics or Druids, though that does not preclude use by most others.

Aura's enhancements have coated the Staff Mace with a plating of pure silver from the Werebane dagger, making it an effective weapon against lycanthropes.

STATISTICS:

THAC0: +2, +5 vs. lycanthropes
Damage: 2d4+2, +5 vs. lycanthropes
Damage type: Crushing
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: One-handed
Requires:
 3 Strength

Weight: 5~

COPY ~%MOD_FOLDER%/items/c0auim04.itm~ ~override~
SAY NAME1 ~Idol~
SAY NAME2 ~Idol of Kozah~
SAY DESC ~This idol depicts Kozah the Stormstar, a long-extinct god who was venerated and feared among the less-powerful strata of ancient Netherese society. Worship of this god of storms, earthquakes, strife, and rebellion was outlawed by many of the civilization's powerful archwizards. Many Kozahyn shrines and temples were therefore built in secretive, underground locations where the devout were better able to escape detection.

Aura's tinkering has somehow awakened a part of the power that lingers within the idol, making it a useful magical item. While held in one's hand, the idol can call down bolts of lightning from the sky to strike down enemies around them or create a Storm Shield around the bearer. However, the bearer's mind is wearied from constant battling against the rage induced by holding the idol close.

STATISTICS:

Charge abilities:
– Call Lightning three times per day
– Storm Shield once per day

Equipped abilities:
– May only be removed with a Remove Curse spell
– Wearer is immune to lightning strikes, Call Lightning and Lightning Bolt
– Electricity Resistance: +20%
– All electrical damage inflicted by the wearer is increased by 15%
– Save vs. Spells: -3 penalty

Weight: 1~

COPY ~%MOD_FOLDER%/items/c0auim05.itm~ ~override~
SAY NAME1 ~Quarterstaff~
SAY NAME2 ~The Ossifier~
SAY DESC ~Cursed Staff of Petrification: The Ossifier
The surface of this seven-foot shaft more resembles stone than wood, but in the hands of a skilled wielder it weighs little more than a staff of oak. Along its length appear the ghost-like images of various foes caught in defensive postures, appearing almost as thought they had been suddenly turned to stone.

Aura's enhancements have managed to turn the cursed weapon into something more beneficial, albeit still largely useless.

STATISTICS:

Equipped abilities:
– May only be removed by a Remove Curse spell
– Stoneskin on user when equipped (five skins, re-applied upon re-equipping)
– Barkskin (base AC set to 6)

Combat abilities:
– 1% chance to petrify target on strike on a failed save vs. spell

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4~

COPY ~%MOD_FOLDER%/items/c0auim06.spl~ ~override~
COPY ~%MOD_FOLDER%/items/c0auim06.itm~ ~override~
SAY NAME1 ~Two-handed Sword~
SAY NAME2 ~Gold Miner +3~
SAY DESC ~Crafted by dwarves in service to the temple of Waukeen in Amn, this two-handed sword draws power from the gold in its wielder's purse. For the wealthy it strikes mighty blows. For the impoverished, the Gold Digger is no better than a mundane greatsword.

Aura's enhancements have somehow managed to reverse-engineer the weapon's enchantments, causing large showers of gold coins to burst from the bodies of the fallen and starting a gold frenzy in the wielder, urging them to kill more quickly.

STATISTICS:

Special:
– Consumes 10 gold per successful hit
– Upon killing a target, gain 100 gold and deal +4 melee damage for the next round.

THAC0: +3
Damage: 1d10+4 (slashing)
Speed Factor: 9
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength
Weight: 15~