COPY ~%MOD_FOLDER%/2da~ ~override~
COPY ~%MOD_FOLDER%/audio~ ~override~
COPY ~%MOD_FOLDER%/bams~ ~override~
COPY ~%MOD_FOLDER%/items~ ~override~
COPY ~%MOD_FOLDER%/portraits~ ~override~
COPY ~%MOD_FOLDER%/eff~ ~override~
COPY ~%MOD_FOLDER%/spells~ ~override~

///////////////////////////////////////////////////////////////////////////////
//////////////////////////////// ANIMATIONS ///////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

ACTION_IF NOT FILE_EXISTS ~MGIRA1.BAM~ THEN BEGIN
COPY ~%MOD_FOLDER%/animations/keg~ ~override~
END

ACTION_IF NOT FILE_EXISTS ~MGIRA1.BAM~ THEN BEGIN
COPY ~%MOD_FOLDER%/animations/golem_iron~ ~override~
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY anims BEGIN
    ~autocannon~ => ~C0_AUTOCANNON~
    ~automaton~ => ~C0_AURA_AUTOMATON~
    ~automaton_jade~ => ~C0_AURA_AUTOMATON_JADE~
    ~automaton_black~ => ~C0_AURA_AUTOMATON_BLACK~
  END
  ACTION_PHP_EACH anims AS folder => symbol BEGIN
    ACTION_BASH_FOR ~%MOD_FOLDER%/animations/%folder%~ ~.+\.bam~ ~%MOD_FOLDER%/animations/%folder%~ ~.+\.bmp~ BEGIN
      COPY ~%BASH_FOR_FILESPEC%~ ~override~
    END
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/animations/%folder%/7xxx.ini~ ~override/%hexNumber%.ini~
    OUTER_SET EVAL ~slot_%folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x%hexNumber% %symbol%~
END

ACTION_IF (NOT GAME_IS_BGEE) BEGIN
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xe000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% C0_AUTOMATON_SMALL~ UNLESS ~C0_AUTOMATON_SMALL~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/automaton_small/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/automaton_small~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
END

ACTION_IF (NOT GAME_IS_BGEE) BEGIN
  LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xe000 slotMax = 0xefff RET slot END
  ACTION_IF (slot <= 0) BEGIN
  END

  LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
  APPEND ~animate.ids~ ~0x%hexNumber% C0_AUTOMATON_LARGE~ UNLESS ~C0_AUTOMATON_LARGE~
  CLEAR_IDS_MAP

  COPY ~%MOD_FOLDER%/animations/automaton_large/exxx.ini~ ~override/%hexNumber%.ini~

  ACTION_BASH_FOR ~%MOD_FOLDER%/animations/automaton_large~ ~^.+\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END
END

///////////////////////////////////////////////////////////////////////////////
/////////////////////////////// RESISTANCES ///////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

DEFINE_ACTION_FUNCTION	ADD_SPLPROT	INT_VAR	stat = 0	value = 0	relation = 0	RET	new_row		BEGIN
	ACTION_IF	(stat > 278)	BEGIN	WARN	~SPLPROT.2DA - Stat out of Bounds.~	END
	ACTION_IF	((stat != 259) AND (stat != 260) AND (relation > 11))	BEGIN	WARN	~SPLPROT.2DA - Relation out of Bounds.~	END
	COPY_EXISTING ~SPLPROT.2DA~	~override~
		COUNT_2DA_COLS	cols
		COUNT_2DA_ROWS cols rows
		TEXT_SPRINT check_row ~~
		TEXT_SPRINT check_stat ~~
		SET new_row = 0
		FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
			PATCH_IF (~%check_stat%~ STRING_EQUAL ~%stat%~)	BEGIN	READ_2DA_ENTRY current_row 2 cols check_value
				PATCH_IF (~%check_value%~ STRING_EQUAL ~%value%~)	BEGIN	READ_2DA_ENTRY current_row 3 cols check_relation
					PATCH_IF (~%check_relation%~ STRING_EQUAL ~%relation%~)	BEGIN	new_row = current_row	current_row = rows	END
				END
			END
		END
		PATCH_IF (new_row = 0)	BEGIN
			FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
				PATCH_IF (~%check_stat%~ STRING_EQUAL ~*~)	BEGIN	new_row = current_row	current_row = rows	END
			END
			PATCH_IF (new_row = 0)	BEGIN	new_row = rows	INSERT_2DA_ROW rows cols ~%new_row%		   %stat%		   %value%		   %relation%~
			END	ELSE	BEGIN	SET_2DA_ENTRY new_row 1 cols ~%stat%~	SET_2DA_ENTRY new_row 2 cols ~%value%~	SET_2DA_ENTRY new_row 3 cols ~%relation%~	END
		END
	BUT_ONLY
END
//	Array of Restistance / Stat#
ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY	BEGIN
	~CRUSH~		=>	22
	~ACID~		=>	17
	~COLD~		=>	15
	~ELEC~		=>	16
	~FIRE~		=>	14
	~PIERC~		=>	23
	~POISN~		=>	74
	~MAGIC~		=>	73
	~MSSL~		=>	24
	~SLASH~		=>	21
	~MFIRE~		=>	19
	~MCOLD~		=>	20
END
ACTION_PHP_EACH	DMG_ARRAY AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 100	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 128	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY2	BEGIN
	~FIRE2~		=>	14
END
ACTION_PHP_EACH	DMG_ARRAY2 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 0	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 128	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

///////////////////////////////////////////////////////////////////////////////
////////////////////////////////// ICONS //////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Frozen~) STR_VAR bam_file = c0aicon1 RET c0aicon1 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Detecting Magic~) STR_VAR bam_file = c0aicon2 RET c0aicon2 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Aflame~) STR_VAR bam_file = c0aicon3 RET c0aicon3 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Magatama~) STR_VAR bam_file = c0aicon4 RET c0aicon4 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Grand Artifice~) STR_VAR bam_file = c0aicon5 RET c0aicon5 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Shocked~) STR_VAR bam_file = c0aicon6 RET c0aicon6 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Guardian Angel~) STR_VAR bam_file = c0aicon7 RET c0aicon7 = icon END

///////////////////////////////////////////////////////////////////////////////
////////////////////////////// PROJECTILES ////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0aproj0.PRO~ ~C0 Grenade~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb1.PRO~ ~C0 Green Flaming Oil~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb2.PRO~ ~C0 Flashbomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb3.PRO~ ~C0 Spiked Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb4.PRO~ ~C0 Sulfur Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb5.PRO~ ~C0 Red Smoke~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb6.PRO~ ~C0 Adhesive Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb7.PRO~ ~C0 Acid Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb8.PRO~ ~C0 Purple Firebomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abomb9.PRO~ ~C0 Big Boom Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro1.PRO~ ~C0 Healing Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro2.PRO~ ~C0 Lightning Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auar02.PRO~ ~C0 Lightning Arrow Chain 1~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0lchain.PRO~ ~C0 Lightning Arrow Chain 2~
COPY_EXISTING ~c0auar02.pro~ ~override~
WRITE_SHORT 0x21A (IDS_OF_SYMBOL (~projectl~ ~c0lchain~)) + 1
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro3.PRO~ ~C0 Static Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro4.PRO~ ~C0 Trollbane Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro5.PRO~ ~C0 Disruptor Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro6.PRO~ ~C0 Warp Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro7.PRO~ ~C0 Detonator Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro8.PRO~ ~C0 Energy Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auaro9.PRO~ ~C0 Ice Arrow~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0arain.PRO~ ~C0 Arrow Volley~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0achain.PRO~ ~C0 Chain Lightning~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0athund.PRO~ ~C0 Thunderbolt~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0athun2.PRO~ ~C0 Thunderbolt~
COPY_EXISTING ~c0athun2.pro~ ~override~
WRITE_SHORT 0x21A (IDS_OF_SYMBOL (~projectl~ ~c0athund~)) + 1
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0aburst.PRO~ ~C0 Burst Orb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0asvoid.PRO~ ~C0 Screaming Void~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0aarea1.PRO~ ~C0 Reveal Magic~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abombb.PRO~ ~C0 EMP Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0abombc.PRO~ ~C0 Phaser Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0aglue.PRO~ ~C0 Glue Bomb~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auimb.PRO~ ~C0 Arcane Disjunctor~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0akeg1.PRO~ ~C0 Exploding Keg~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0ausp02.PRO~ ~C0 Poison Haze~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0ausp03.PRO~ ~C0 Poison Blast~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0acone1.PRO~ ~C0 Igneus Blaze 1~
COPY_EXISTING ~c0acone1.pro~ ~override/c0acone2.pro~
WRITE_BYTE 0x224 60
COPY_EXISTING ~c0acone1.pro~ ~override/c0acone3.pro~
WRITE_BYTE 0x224 90
ADD_PROJECTILE ~override/c0acone2.PRO~ ~C0 Igneus Blaze 2~
ADD_PROJECTILE ~override/c0acone3.PRO~ ~C0 Igneus Blaze 3~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0acryo1.PRO~ ~C0 Cryoshock~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0amiss1.PRO~ ~C0 Energy Barrage 1~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0amiss2.PRO~ ~C0 Energy Barrage 2~
COPY_EXISTING ~c0amiss2.pro~ ~override/c0amiss3.pro~
COPY_EXISTING ~c0amiss2.pro~ ~override/c0amiss4.pro~
COPY_EXISTING ~c0amiss2.pro~ ~override/c0amiss5.pro~
COPY_EXISTING ~c0amiss2.pro~ ~override/c0amiss6.pro~
COPY_EXISTING ~c0amiss2.pro~ ~override/c0amiss7.pro~
COPY_EXISTING ~c0amiss2.pro~ ~override/c0amiss8.pro~
ADD_PROJECTILE ~override/c0amiss3.PRO~ ~C0 Energy Barrage 3~
ADD_PROJECTILE ~override/c0amiss4.PRO~ ~C0 Energy Barrage 4~
ADD_PROJECTILE ~override/c0amiss5.PRO~ ~C0 Energy Barrage 5~
ADD_PROJECTILE ~override/c0amiss6.PRO~ ~C0 Energy Barrage 6~
ADD_PROJECTILE ~override/c0amiss7.PRO~ ~C0 Energy Barrage 7~
ADD_PROJECTILE ~override/c0amiss8.PRO~ ~C0 Energy Barrage 8~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0albolt.PRO~ ~C0 Aerial Judgment~
ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0albol2.PRO~ ~C0 Aerial Judgment 2~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0pring.PRO~ ~C0 Panacea Circle~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0acomet.PRO~ ~C0 Red Meteor~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/pro/c0auheal.PRO~ ~C0 Aura Healing~